### ISSUE TITLE
Issue with Odoo Docker Image and Usage Clarification

### ISSUE THREAD

**Issue by Crackboomlaboom** [odoo-it/docker-odoo#26]
---
[inspect.txt](https://github.com/odoo-it/docker-odoo/files/12703728/inspect.txt)

**Issue Summary:**

I encountered an issue while attempting to utilize your Odoo Docker image. After successfully building the image, I noticed that the container failed to start due to a potential misconfiguration.

The error message I received is as follows:

```
Preparing environment...
/home/odoo/.resources/entrypoint.d/600-wait-postgress:
Waiting for postgres to be ready...
db:5432 - no response
run-parts: /home/odoo/.resources/entrypoint.d/600-wait-postgress exited with return code 2
```

**Request for Clarification:**

I would greatly appreciate guidance on how to properly use this Docker image. Specifically, I'd like to understand if the image is designed to automatically start Postgres alongside the container, or if Postgres is expected to be set up separately.

Your assistance in resolving this issue and providing usage instructions would be highly appreciated.

Thank you for your attention to this matter.

Best regards,

Kingsley
crackboomlaboom

**Comment by ivantodorovich** [comment]
Hello! 👋🏻 

The image does not include postgres in it, but it requires it to be deployed along side with it
I'm including some usage examples here: 
- https://github.com/odoo-it/docker-odoo/pull/28

I'd love your thoughts on the added example

Best
